name = "physme"
description = "A simplistic physics engine for 2D/3D sims. Physically inaccurate, but satisfying and easy to use."
link = "https://github.com/walterpie/physme"
bevy_versions = ["0.3"]
licenses = ["MIT"]
