name = "bevy_input_actionmap"
description = "Maps key and gamepad events to actions in Bevy."
link = "https://github.com/lightsoutgames/bevy_input_actionmap"
bevy_versions = ["0.7"]
licenses = ["MIT", "Apache-2.0"]
