name = "bevy_simple_networking"
description = "A simple authoritative server networking library for Bevy"
link = "https://github.com/bacongobbler/bevy_simple_networking"
bevy_versions = ["0.7.0"]
licenses = ["Apache-2.0"]
