name = "bootleg_networking"
description = "A completely cross-platform networking plugin utilizing TCP/UDP and bevy_networking_turbulence"
link = "https://github.com/billyb2/bootleg_networking"
bevy_versions = ["0.7"]
licenses = ["MIT"]
