name = "bevy_tileset"
description = "Simple, configurable tilesets in Bevy using RON."
link = "https://github.com/MrGVSV/bevy_tileset"
image = "bevy_tileset.gif"
bevy_versions = ["0.4"]
licenses = ["MIT", "Apache-2.0"]
