name = "bevy_pixels"
description = "A plugin that uses Pixels (a tiny pixel buffer) for rendering."
link = "https://github.com/dtcristo/bevy_pixels"
bevy_versions = ["0.7"]
licenses = ["MIT", "Apache-2.0"]
