name = "bevy_ecs_ldtk"
description = "An ergonomic and ECS-friendly ldtk plugin!"
link = "https://github.com/Trouv/bevy_ecs_ldtk"
image = "bevy_ecs_ldtk.gif"
bevy_versions = ["0.7"]
licenses = ["MIT", "Apache-2.0"]
