name = "bevy-sequential-actions"
description = "A Bevy library for executing various actions in a sequence."
link = "https://github.com/hikikones/bevy-sequential-actions"
bevy_versions = ["0.7"]
licenses = ["MIT", "Apache-2.0"]
