name = "Tetris for Bevy 0.6 / 0.7"
description = "A partial Tetris clone written as an introductory tutorial for Bevy 0.6 / 0.7"
link = "https://github.com/langp11/bevy-tetris-0.6"
image = "bevy-tetris-0.6.png"
bevy_versions = ["0.7"]
licenses = ["MIT", "Apache-2.0"]
