name = "Cheaters Never Win"
description = "A infinite runner built in 7 days for the Bevy Jam #1"
link = "https://github.com/TheRealTeamFReSh/Cheaters-Never-Win"
image = "cheaters-never-win.png"
bevy_versions = ["0.6.0"]
